In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:

#評価関数
def _sphere(x):
    return torch.pow(x,2).sum()


In [169]:
class Model(nn.Module):
    def __init__(self,dim =100,func =None):
        super(Model,self).__init__()
        if func is None:
            func = _sphere
        self.func = func
        #設計変数
        self.x = nn.Parameter(torch.rand(dim))
        
    def forward(self):
        return self.func(self.x)
    
    def vars(self):
        return self.x.detach().numpy()
    
    def objective(self):
        with torch.no_grad():
            return self.func(self.x).numpy()

In [170]:

model = Model(dim=2)
optimizer = optim.RMSprop(model.parameters(),lr=0.1)

In [171]:
N = 100

print('初期の評価値',model.objective())

初期の評価値 1.8387789


In [172]:
print('変数',model.x)

変数 Parameter containing:
tensor([0.9878, 0.9290], requires_grad=True)


In [173]:
model.x.size()

torch.Size([2])

In [174]:

print('optimization...')
for i in range(N):
    output = model()
    optimizer.zero_grad()
    loss = output
    loss.backward()
    optimizer.step()
    print('loss:',loss.item(),end='\n')
    
print()

print('評価値',model.objective())

optimization...
loss: 1.8387788534164429
loss: 0.005190227646380663
loss: 3.124859358649701e-05
loss: 2.2065832183670864e-07
loss: 1.7693191356471516e-09
loss: 1.5980885018085367e-11
loss: 1.6158744535563901e-13
loss: 1.819004313019794e-15
loss: 2.268406014253362e-17
loss: 3.1196778175374175e-19
loss: 4.7121405842623756e-21
loss: 7.787774326949872e-23
loss: 1.4034502091346712e-24
loss: 2.7490751759574604e-26
loss: 5.83588165807426e-28
loss: 1.3389677358917068e-29
loss: 3.3119003203061766e-31
loss: 8.810491789886283e-33
loss: 2.5152417670641714e-34
loss: 7.689843835859767e-36
loss: 2.5128716328139723e-37
loss: 8.760831118453968e-39
loss: 3.2530863589607763e-40
loss: 1.2844301724001273e-41
loss: 5.3809861030072976e-43
loss: 2.382207389352189e-44
loss: 1.401298464324817e-45
loss: 0.0
loss: 0.0
loss: 0.0
loss: 0.0
loss: 0.0
loss: 0.0
loss: 0.0
loss: 0.0
loss: 0.0
loss: 0.0
loss: 0.0
loss: 0.0
loss: 0.0
loss: 0.0
loss: 0.0
loss: 0.0
loss: 0.0
loss: 0.0
loss: 0.0
loss: 0.0
loss: 0.0
loss: 0.

In [175]:

model.x


Parameter containing:
tensor([-2.8026e-45,  5.6052e-45], requires_grad=True)

In [176]:
model.vars()

array([-3.e-45,  6.e-45], dtype=float32)

In [220]:

x = torch.tensor([1.],requires_grad=True)
loss_func = nn.MSELoss()
optimizer = optim.SGD([x],lr=0.1)
target = torch.tensor([0.])

In [223]:

for iter_num in range(100):
    optimizer.zero_grad()
    y = x**2-2
    loss = loss_func(y,target)
    loss.backward()
    print("{0}: x={1:.7f}, y={2:.7f},dL/dx={3:.7f}".format(iter_num,x.data.numpy()[0],y.data.numpy()[0],x.grad.data.numpy()[0]))
    optimizer.step()

0: x=1.4142137, y=0.0000002,dL/dx=0.0000013
1: x=1.4142135, y=-0.0000001,dL/dx=-0.0000007
2: x=1.4142137, y=0.0000002,dL/dx=0.0000013
3: x=1.4142135, y=-0.0000001,dL/dx=-0.0000007
4: x=1.4142137, y=0.0000002,dL/dx=0.0000013
5: x=1.4142135, y=-0.0000001,dL/dx=-0.0000007
6: x=1.4142137, y=0.0000002,dL/dx=0.0000013
7: x=1.4142135, y=-0.0000001,dL/dx=-0.0000007
8: x=1.4142137, y=0.0000002,dL/dx=0.0000013
9: x=1.4142135, y=-0.0000001,dL/dx=-0.0000007
10: x=1.4142137, y=0.0000002,dL/dx=0.0000013
11: x=1.4142135, y=-0.0000001,dL/dx=-0.0000007
12: x=1.4142137, y=0.0000002,dL/dx=0.0000013
13: x=1.4142135, y=-0.0000001,dL/dx=-0.0000007
14: x=1.4142137, y=0.0000002,dL/dx=0.0000013
15: x=1.4142135, y=-0.0000001,dL/dx=-0.0000007
16: x=1.4142137, y=0.0000002,dL/dx=0.0000013
17: x=1.4142135, y=-0.0000001,dL/dx=-0.0000007
18: x=1.4142137, y=0.0000002,dL/dx=0.0000013
19: x=1.4142135, y=-0.0000001,dL/dx=-0.0000007
20: x=1.4142137, y=0.0000002,dL/dx=0.0000013
21: x=1.4142135, y=-0.0000001,dL/dx=-0.000000

In [224]:
x.data.numpy()[0]

1.4142137